Repository Ameesha15/DSA-ALGORITHMS, pull requests merged in 2020-10, with the labels that each got.

#4 Create TreeSearch.java
  TreeSearch.java
Labels: enhancement, hacktoberfest-accepted

#6 Create ProirityQueue.java
  ProirityQueue.java
Labels: hacktoberfest-accepted

#5 CircularQueue.java
  CircularQueue.java
Labels: hacktoberfest-accepted

#8 NodeAlgo.java
  NodeAlgo.java
Labels: enhancement, good first issue, hacktoberfest-accepted
